namespace TimeParabox;

/// <summary>
/// Challenge / Side / Appendix (+ Challenge & Gallery worlds) solutions
/// converted from the Steam/GamePretty UDLR walkthrough (nana / geerky42 et al.).
/// Enter the puzzle manually, then: TimeParabox.exe --extra "Enter" 5
/// </summary>
public static class ExtraPuzzles {

    public record ExtraPuzzle(string hub, int id, string kind, string actions);

    public static readonly IReadOnlyList<ExtraPuzzle> ALL = new List<ExtraPuzzle> {
        new("Enter", 5, "challenge", "^<v>>>v<<v<^>^<<^<<v>>>>v>>^<v<^^vvv<"),
        new("Enter", 8, "challenge", "<^^>>^>vv>>^<^<vv>v<^<<vv>^^^^<^>>>>>>>^^vv<<<<<<^"),
        new("Enter", 9, "challenge", ">^^^>vvv>v<<>>v<<^^^^^<vvvv<<>>>v>^^^<^>>>^^"),
        new("Enter", 10, "challenge", "^>>v^>>vv>v<>v<<<<vv<^^^<^><^><^>vvvvvv>>^v>>>^<<<v<^^^^>>"),
        new("Enter", 17, "challenge", "^^>>>>>>^^>>>>>>^^<<^^^^<^>>>>>^>>>vvv>>vvvv<vv>^^^^^v<<<<<vvvvv>>^"),
        new("Enter", 18, "challenge", "^^>^<^<<v>>>><<^^>v<vvvvv>vv>^<<<v<^>^<^<vv<vvv>"),
        new("Empty", 5, "challenge", "<vvv>^<^>>>>v>^<<<^>^>v<v>v>^^<^><<vvv<^<^>>v>^^<^^>vv^^>vv>v"),
        new("Empty", 6, "challenge", "^^<<vvvv<<<>>>>^^^^>vvvv>>><<^<v<vv>^^^^^"),
        new("Empty", 7, "challenge", ">>v>^^^>^<vv<^v<<<^>>v>^>^<v<^^^>>><<^<<<v><vv>^<^>>><<"),
        new("Empty", 10, "challenge", "<^^>v>>v<<<<v<<^v>>^<v<^>>>v<^>^^<<v>>v>^^^^>^<<<<^>>>>>>>v>^>^^<vvv<"),
        new("Empty", 11, "challenge", ">vv<<^>^>vv>v<<<<<<vvv^^^>^<<<^^vvvvv^^>^<<<<>vvv>"),
        new("Empty", 13, "challenge", "<^^^^vv<<<<>vvv>>vv>v<^<vv^^^^<^^>>^<<vvv>>>>"),
        new("Empty", 14, "challenge", "<<<v>>^>vvvv^^^>>>^<>^^<v<<<<<^>>v>^^^vv>>>v<<>>vv<<^v>^>^<vv>"),
        new("Eat", 8, "challenge", "^<<<v>>^>vvvv^^>>><<v<^<vv^>^^^^>^<v<^^v>>^^<<<<<^<vvv^^>>>>vv>^>^<<<<^<vv^>>>>>>>vvv>><^<vv^^^>>>>>vvvvvv<<v<^^^^"),
        new("Eat", 11, "challenge", ">vvv<^<^>>><vv>^<^>>v>^<<<^^>v<v>>v>^^^vv>^<<<v<^<^>>^>vvv<<<<v"),
        new("Eat", 12, "challenge", "v>^>vvv^<<v>v<<<^^>>>^>v>v<<v<^v<<^>>><<^>><<<^>^>vvvv^^^>>vv>v<<^<vvv"),
        new("Eat", 13, "side", "^>>>>^^^^^^<<<<<<v<<^>>>>>>><<<v>^^^>^^<vvvvvv<vvv>"),
        new("Reference", 4, "challenge", "^<<<v>>v>^^>^<<vvv<<<<^<<^^^^^vvvv<<<^<<>>>>v>>"),
        new("Reference", 5, "challenge", "<<v<^^^<^>>><v<v>>v>^>^<<<<^<vv>>>^^^^<^^<<"),
        new("Reference", 6, "challenge", "^^>>vv<v>><<v>>v>^^^^^vvvv>^<v<^^<^>^>>vv>><^<v<v>vv<"),
        new("Reference", 7, "challenge", "<vvvv<^v>>>^<<v<^^^vv<^>>>>><<<<<^<<v>^^vvvv^^^vv<<<<<<^<<^>vvvvvvvv<<<<^^"),
        new("Reference", 10, "challenge", ">>>>>^^>>>>>>v<<<v<^<>>^<<>vvvv>>>>^<<<<<v<^^^<<<<v<^>vvvvv>vv<>^^<<vvvv>v<v<^^<^>vvv>vvvv<vvv>v<^<vvv^<v>^>^^^^^^^>^^vvvv<<vv>^^^^>^^^^^^^"),
        // Alternate UDLR (SteamAH / mirror guides) — geerky42 path failed in ViGEm testing
        new("Reference", 11, "side", ">vvv>^<<<vv>vv^<^^^^>>v>><<<<<^<v<^^>^>vvv<<v>v>^^^^<^>>>v>^^v>>v><^<<<<<^^^>^^vvvvv>v<<<<<^<vv<v"),
        new("Reference", 12, "side", "v<<<v>>v>^^vv>^^>^<<<>>^<vvv>v<^<vv^^^>^^<^^<v<<>^^^^>^^<^^>v<<<<^^<<<"),
        new("Swap", 2, "normal", "vvv>>^<<<<<v>>^>vv^>>^>^<<<<v<^>>>>>^<<<<<<<v<^^^^^^^<<vvv<v>>^>vvv>v<v<^^<^>>v>^v>><<<<<vv"),
        new("Swap", 3, "challenge", "v>>>^<v<^^<<^>>>>>><<<<^>>vvv>v<<^<vv^^^^>>>>>v>^^^^^^>>vvv>v<<^<vvv<v><"),
        new("Swap", 4, "challenge", "^^^>^^<vvv>v<v<<^^^>^^<vvvv<<v>v>>^v<<^>v>^^^^>^^<<<vv<<<<^>>>v>^<^>>>vvv^^>>^<^<v>v<<>vvv^^^^^<<<vv>>>v>^>^<<<<<v<^>^<<<>>>>v>>v<^^<^>^>vvvvvvvv"),
        new("Swap", 5, "challenge", "v>v>^>^^^<<vv<<<v>>>><<^^^<v<v>>>>><vv>^<^>>><>^>>>>vv>v<<<^<<^^>v^>>>v<^<<v^>>v<^<vvvv>v<>v<>v<v<^^^^^<^>v>^^^<<v>vvvv>^^^<v>>v>^^>^<<<<<<vvvv<^>v>^^^>"),
        new("Center", 5, "challenge", "^^<<<<vvvvvvv<v>>>>^>v<vv>^^^>>v"),
        new("Center", 7, "challenge", "<vvv^^^^<v>vvv>>>>>><^^^^vv<v>^^^>>>>>v>^^<^>v>"),
        new("Center", 10, "challenge", "vv>>^^^>>^^^<<^<v<<vv>vv<<^^>>>>vv>"),
        new("Center", 11, "challenge", "vv<^<^>>>>>^^<v<v>>>^>v<v><<<<^^<v<v>>>>>^>vv<v><<<v<v>>^^^>vv>>>"),
        new("Center", 12, "challenge", "^^<vvvv^>v<<<^<^^^vvvv>>><<<<<<<<^>v>^^^^>"),
        new("Center", 13, "challenge", ">vv^<<<v>>^>v>v<<<<^<v<v>^><vvv^<^>>>>>^>vvvv<v>vv>><<<^>>>>>^^^^^>"),
        new("Center", 14, "challenge", "<<v^^<<vv>>>v<<<<^<<vv>^<^>v>>>^^^<vv>v<^<vvvv>v<^^^<<<v>>><<^>>"),
        new("Center", 15, "side", ">>>vv<<^>^vvv^^^<v>>v>>>^<<<<<^^^>^>"),
        new("Center", 16, "side", ">>vv>>^<v<^>^<<<<<<<<<<^^<<v>>v<^<vv^>>>>>>>>>>>v>>^><v<<^<<<<<<<<<^^>"),
        // Clone 1-25 (Steam: 14 & 16 are challenges; any% skips many)
        new("Clone", 1, "normal", "vvvvv>>^^^^>>^>vvvv^^^<<<vvvv<<^^^<^"),
        new("Clone", 2, "normal", "^^<<<<vv^^^>>>>^><>>>^^^^>>>^v^^^^>^<v<^<<^"),
        new("Clone", 3, "normal", ">vv<^<vv>>v<<<v<<^<>v>vv<^^vvv"),
        new("Clone", 4, "normal", "<^^^>vv<v>v>^>>>^^^<<<<<<^<<v<<<<<v<^^^^v>>^^<<vvv<<<<v<<^<<<vvv<<<vvvv<<^^"),
        new("Clone", 5, "challenge", "<<^>>^>vvv<v>>><<<<<^>>v>^^^^v^^^vv<<<<^^^^><"),
        new("Clone", 6, "challenge", "<vvv>^<^>>v>^^^^>>v<^<^^^^>^<v<^^^^^"),
        new("Clone", 7, "normal", ">v<^^<^>>vvvv<<v<>>"),
        new("Clone", 8, "normal", "^<vv>^^<^>>>>><<vvv^v<<<<vvv>><<<<"),
        new("Clone", 9, "normal", "<vv>^>vvv<v>>>^>vv<v>>>>>v>"),
        new("Clone", 10, "normal", "^^<<vvv>>vvvv<v>^>v<^^^^>^<<<<"),
        new("Clone", 11, "normal", ">vvv>>^^>^<^>>^^<v<v>>>>vv>>>v>>^^^^^>>>v<v>><<<<vvv<<^<^^>^<<>v<v<^^>^^^<"),
        new("Clone", 12, "challenge", "<<<vv><vvv>^^<^>>>v>^^^>^<<vvv<<^>vv<v>>>>^>vvv^^^^^<<<<>>v>^^^^^"),
        new("Clone", 13, "normal", "^^>>>vvv>><<<<<>vvv<<>>>>>><<<vvv<<<<<vv>"),
        new("Clone", 14, "challenge", ">>>>v<<<>>>><vvv>>>>>^>>^^>>>^>>v>^>^^><vv<<<<v>^^>>>^>>^^>>>^>>vv>"),
        new("Clone", 15, "normal", "<^^^>v<v>>>v>^<<^>>>>>>^^<v>v<<<<<<^>v^<<<v>>vv>>^<v<^<^>>>>>>^>vvv^^<<<<<<<"),
        new("Clone", 16, "challenge", "<vvv>^>>^^^^>>v<^<vvv<^>>v>^<<<vvv>^<^>>^>^^^^^>^<<>vvvvvv"),
        new("Clone", 17, "challenge", ">v>^<^><^^>v<^<v<v>>>>^>vv<<vvvv>vv<<^>>>>v>^^^<<^<^^>^^"),
        new("Clone", 18, "challenge", "v<<^>>>>v<^^^>^>^>^^^^>v^<<<<vv<<^>>^^<<"),
        new("Clone", 19, "normal", ">^^^<v>v<<^^<vv<v>^>vv>v<v<^^vv<^>v>^^^^^<v>>v>^^>^<"),
        new("Clone", 20, "normal", "^^>>^<vv<<<vvvv<<^>vv>vv<<vv<v>>^>v^>v<<<<vvv<<"),
        new("Clone", 21, "challenge", "<<<vvvv>^>>v^<<v><^^>^>vv>>>^^^>^<<<<<<vvvv^>>>^^^>^<<<<<vvv>>^^^>^<<<<vvv>v<^<<v^>>v<>>^^^^>^<<<<<^<vvvv>>>^^^>^<<<<<^<v^<v>>v<<>vvv>>>^^^^>^<<<<<<vv<<<^v>^>^"),
        new("Clone", 22, "challenge", ">v>v<<<<<v<^<^>vv<<^<^>>>>>^>v^>v>v<<<<>>v<^>^<<<<<^<vvv^^>>>>>>><<<^^>v<v>><^^^"),
        new("Clone", 23, "challenge", ">>v>^vvv<<^>v>^^^^^<^>^<^>^>vvvvvvv>v<<>>^^^^^>>v<^<vvv<v>>>>^^^^>^<>vvvvvvvvvv>v<<>>^>>v<<>^^"),
        new("Clone", 24, "side", ">>>^<v<vvv>^^^>^<vvv<<v<^^^<vvv>v<<<<v<^^^^^^<<<vvvvvvvv>v<<<<<v<^^^^^<<>vvv>^<<<<>>>>>><^^^^^"),
        new("Clone", 25, "side", "<<<^^^>>vvvvv>>>vvv<v>>vvv>>v<<>^^^^^>^<<<^<v>>>>>^^^^^^^^>><<^^^^^^"),
