namespace TimeParabox;

/// <summary>
/// Challenge / Side / Appendix (+ Challenge & Gallery worlds) solutions
/// converted from the Steam/GamePretty UDLR walkthrough (nana / geerky42 et al.).
/// Enter the puzzle manually, then: TimeParabox.exe --extra "Enter" 5
/// </summary>
public static class ExtraPuzzles {

    public record ExtraPuzzle(string hub, int id, string kind, string actions);

    public static readonly IReadOnlyList<ExtraPuzzle> ALL = new List<ExtraPuzzle> {
        new("Enter", 5, "challenge", "^<v>>>v<<v<^>^<<^<<v>>>>v>>^<v<^^vvv<"),
        new("Enter", 8, "challenge", "<^^>>^>vv>>^<^<vv>v<^<<vv>^^^^<^>>>>>>>^^vv<<<<<<^"),
        new("Enter", 9, "challenge", ">^^^>vvv>v<<>>v<<^^^^^<vvvv<<>>>v>^^^<^>>>^^"),
        new("Enter", 10, "challenge", "^>>v^>>vv>v<>v<<<<vv<^^^<^><^><^>vvvvvv>>^v>>>^<<<v<^^^^>>"),
        new("Enter", 17, "challenge", "^^>>>>>>^^>>>>>>^^<<^^^^<^>>>>>^>>>vvv>>vvvv<vv>^^^^^v<<<<<vvvvv>>^"),
        new("Enter", 18, "challenge", "^^>^<^<<v>>>><<^^>v<vvvvv>vv>^<<<v<^>^<^<vv<vvv>"),
        new("Empty", 5, "challenge", "<vvv>^<^>>>>v>^<<<^>^>v<v>v>^^<^><<vvv<^<^>>v>^^<^^>vv^^>vv>v"),
        new("Empty", 6, "challenge", "^^<<vvvv<<<>>>>^^^^>vvvv>>><<^<v<vv>^^^^^"),
        new("Empty", 7, "challenge", ">>v>^^^>^<vv<^v<<<^>>v>^>^<v<^^^>>><<^<<<v><vv>^<^>>><<"),
        new("Empty", 10, "challenge", "<^^>v>>v<<<<v<<^v>>^<v<^>>>v<^>^^<<v>>v>^^^^>^<<<<^>>>>>>>v>^>^^<vvv<"),
        new("Empty", 11, "challenge", ">vv<<^>^>vv>v<<<<<<vvv^^^>^<<<^^vvvvv^^>^<<<<>vvv>"),
        new("Empty", 13, "challenge", "<^^^^vv<<<<>vvv>>vv>v<^<vv^^^^<^^>>^<<vvv>>>>"),
        new("Empty", 14, "challenge", "<<<v>>^>vvvv^^^>>>^<>^^<v<<<<<^>>v>^^^vv>>>v<<>>vv<<^v>^>^<vv>"),
        new("Eat", 8, "challenge", "^<<<v>>^>vvvv^^>>><<v<^<vv^>^^^^>^<v<^^v>>^^<<<<<^<vvv^^>>>>vv>^>^<<<<^<vv^>>>>>>>vvv>><^<vv^^^>>>>>vvvvvv<<v<^^^^"),
        new("Eat", 11, "challenge", ">vvv<^<^>>><vv>^<^>>v>^<<<^^>v<v>>v>^^^vv>^<<<v<^<^>>^>vvv<<<<v"),
        new("Eat", 12, "challenge", "v>^>vvv^<<v>v<<<^^>>>^>v>v<<v<^v<<^>>><<^>><<<^>^>vvvv^^^>>vv>v<<^<vvv"),
        new("Eat", 13, "side", "^>>>>^^^^^^<<<<<<v<<^>>>>>>><<<v>^^^>^^<vvvvvv<vvv>"),
        new("Reference", 4, "challenge", "^<<<v>>v>^^>^<<vvv<<<<^<<^^^^^vvvv<<<^<<>>>>v>>"),
        new("Reference", 5, "challenge", "<<v<^^^<^>>><v<v>>v>^>^<<<<^<vv>>>^^^^<^^<<"),
        new("Reference", 6, "challenge", "^^>>vv<v>><<v>>v>^^^^^vvvv>^<v<^^<^>^>>vv>><^<v<v>vv<"),
        new("Reference", 10, "challenge", ">>>>>^^>>>>>>v<<<v<^<>>^<<>vvvv>>>>^<<<<<v<^^^<<<<v<^>vvvvv>vv<>^^<<vvvv>v<v<^^<^>vvv>vvvv<vvv>v<^<vvv^<v>^>^^^^^^^>^^vvvv<<vv>^^^^>^^^^^^^"),
        new("Reference", 11, "side", "v<<<^>>>>vvv>^<<<vv>vv^<<^^^^>>>v>><<v<^^<^>v>^^^v>>v><^<<<<<^^^>^^vvvvv>v<<<<<^<vv<v"),
        new("Reference", 12, "side", "v<<<v>>v>^^vv>^^>^<<<>>^<vvv>v<^<vv^^^>^^<^^<v<<>^^^^>^^<^^>v<<<<^^<<<"),
        new("Swap", 3, "challenge", "v>>>^<v<^^<<^>>>>>><<<<^>>vvv>v<<^<vv^^^^>>>>>v>^^^^^^>>vvv>v<<^<vvv<v><"),
        new("Swap", 4, "challenge", "^^^>^^<vvv>v<v<<^^^>^^<vvvv<<v>v>>^v<<^>v>^^^^>^^<<<vv<<<<^>>>v>^<^>>>vvv^^>>^<^<v>v<<>vvv^^^^^<<<vv>>>v>^>^<<<<<v<^>^<<<>>>>v>>v<^^<^>^>vvvvvvvv"),
        new("Swap", 5, "challenge", "v>v>^>^^^<<vv<<<v>>>><<^^^<v<v>>>>><vv>^<^>>><>^>>>>vv>v<<<^<<^^>v^>>>v<^<<v^>>v<^<vvvv>v<>v<>v<v<^^^^^<^>v>^^^<<v>vvvv>^^^<v>>v>^^>^<<<<<<vvvv<^>v>^^^>"),
        new("Center", 5, "challenge", "^^<<<<vvvvvvv<v>>>>^>v<vv>^^^>>v"),
        new("Center", 7, "challenge", "<vvv^^^^<v>vvv>>>>>><^^^^vv<v>^^^>>>>>v>^^<^>v>"),
        new("Center", 10, "challenge", "vv>>^^^>>^^^<<^<v<<vv>vv<<^^>>>>vv>"),
        new("Center", 11, "challenge", "vv<^<^>>>>^^<v<v>>>^>v<v><<<<^^<v<v>>>>>^>vv<v><<<v<v>>^^^>vvv>>>"),
        new("Center", 12, "challenge", "^^<vvvv^>v<<<^<^^vvvv>>><<<<<<<<^>v>^^^^>"),
        new("Center", 13, "challenge", ">vv^<<<v>>^>v>v<<<^<v<v>^><vvv^<^>>>>^>vvvv<vv>>><<<^>>^^^^^^>"),
        new("Center", 14, "challenge", "<<v^^<<vv>>>v<<<^<<vv>^<^>v>>>^^^<vv>v<^<vvv>v<^^<<<v>>><<^>>^>>"),
        new("Center", 15, "side", ">>>vv<<^>^vvv^^^<v>>v>>>^<<<<<<^^>^>"),
        new("Center", 16, "side", ">>vv>>^<v<^>^<<<<<<<<^^<<v>>v<^<vv^>>>>>>>>>>v>>^><v<<^<<<<<<<^^>"),
        new("Clone", 12, "challenge", "<<<vv><vvv>^^<^>>>v>^^^>^<<vvv<<^>vv<v>>>>^>vvv^^^^^<<<<>>v>^^^^^"),
        new("Clone", 17, "challenge", ">v>^<^><^^>v<^<v<v>>>>^>vv<<vvvv>vv<<^>>>>v>^^^<<^<^^>^^"),
        new("Clone", 18, "challenge", "v<<^>>>>v<^^^>^>^>^^^^>v^<<<<vv<<^>>^^<<"),
        new("Clone", 21, "challenge", "<<<vvvv>^>>v^<<v><^^>^>vv>>>^^^>^<<<<<<vvvv^>>>^^^>^<<<<<vvv>>^^^>^<<<<vvv>v<^<<v^>>v<>>^^^^>^<<<<<^<vvvv>>>^^^>^<<<<<^<v^<v>>v<<>vvv>>>^^^^>^<<<<<<vv<<<^v>^>^"),
        new("Clone", 22, "challenge", ">v>v<<<<<v<^<^>vv<<^<^>>>>>^>v^>v>v<<<<>>v<^>^<<<<<^<vvv^^>>>>>>><<<^^>v<v>><^^^"),
        new("Clone", 23, "challenge", ">>v>^vvv<<^>v>^^^^^<^>^<^>^>vvvvvvv>v<<>>^^^^^>>v<^<vvv<v>>>>^^^^>^<>vvvvvvvvvv>v<<>>^>>v<<>^^"),
        new("Clone", 24, "side", ">>>^<v<vvv>^^^>^<vvv<<v<^^^<vvv>v<<<<v<^^^^^^<<<vvvvvvvv>v<<<<<v<^^^^^<<>vvv>^<<<<>>>>>><^^^^^"),
        new("Clone", 25, "side", "<<<^^^>>vvvvv>>>vvv<v>>vvv>>v<<>^^^^^>^<<<^<v>>>>>^^^^^^^^>><<^^^^^^"),
        new("Transfer", 5, "challenge", ">^>vvv<<^^^<<v>^>vvvv<v>>>v>^^^<<<<^^>>>"),
        new("Transfer", 8, "challenge", ">v>^<<<^^^>v<v>^^>>v<^<v<v>>>v>>>>>>>^"),
        new("Transfer", 9, "challenge", "<<^<vv>>>>v<<<^^<<<<vvvv>v^>^^<vvv>>vvvv<<<<^<>^^^^>>>"),
        new("Transfer", 10, "challenge", "<v<v>>^^>v<^^>^>vvv^^^<<<<v>>>>^>vvv<<vv>>><<v>>^^>^<<<<<^<vvv>^>>v<^<vvv<<<>^^^^^^>>"),
        new("Transfer", 13, "challenge", ">^^^<vv>v<>>>^^<<^<vv>v<v<^^<^>>><<<<^^^<<>vvv>>"),
        new("Transfer", 14, "challenge", "<^^^>vv<v>v>>>^^<v>v<^^^^^^^<<<<<v<<^>>vv>^>>^<v<<<^^>v<v>v>^^v<^>v>>^^<v>v<vv^^^^^<^>v>^^^^^>^<>>>^^^^^"),
        new("Transfer", 18, "challenge", "^^^>>v>v<^^<<v>vv^>>vv<^^^<<^^^>>vvv<<<<^^^"),
        new("Transfer", 19, "challenge", "^>>>vvvv<^>^<<v<^^>^<^>>v>vv<v<^^^>^<<vvv<vv<^^^>>>^>>v<^<vvv>v>^^^>^<<<vvv<<vvv>>^^^<<<<vvvvvvv<<<<<<<<<<"),
        new("Transfer", 20, "challenge", ">>^^<v>v<^^<v>>vvv<^^>^<^<<<vvvv>^^^<^><^>>vvvvvv>>^^^>>vvv>>^^^"),
        new("Transfer", 24, "challenge", ">^>>^<<^<<vv>>^<^<vvv<v>^>>>>^>vv<<<^^<<v>>>>^>vvv<v><<<<v<<^^>^>>"),
        new("Transfer", 25, "challenge", "v>>v>v<<^^>>^<<^<vvvv>v<<<<<<<<>>>>>>>>v<<<<<<v<^>^<<<<"),
        new("Transfer", 26, "challenge", ">>v>^^^^<^>v>>v<v<^^<<<<v>v>^^<^>>v>v<v<^^>>>>vvv<<<<v<^^^^>>^>^>>v<<^<<<vv"),
        new("Transfer", 27, "side", "<<<v<^>>>vvv>>>>>^^^^>>>vvv>>>^<<vvv<<<^^^>^>vvv<v>>>>>>"),
        new("Transfer", 28, "side", "^^<^<<<vv>vv>vv<^^>^<^<<<vv>v>>>v>>^<<v<^<^<^^>>>v>>>vvvv<^^<<v>>^v^^<"),
        new("Transfer", 29, "side", "^>^^>vvvv>v<<<^^^^^<vvvvvv>vvv<<<>>^^^>><>^^<v>v<>>"),
        new("Open", 4, "challenge", "v<<<v>>v>^^^^<<<v>>v>>>v<v<^^^^>^<<<^<v>v<>>>vvvvvvv"),
        new("Open", 5, "challenge", "^^>>>^>vvvvv<<<<^^^^<<^<vvv>>>>>>>vvvv<vv><^^>^^<vv^^^^>>>>>>vvvvv>v>^>^<>>"),
        new("Open", 7, "challenge", "v>>>>>>><<<<<>^<<<v><<>>>>^^<<<"),
        new("Open", 8, "challenge", ">>>><<<<<>>>>>>><<<<<<^^^^<vv>>^<^^>v<vvvvvv<^>>>>>><<<^^"),
        new("Open", 9, "challenge", ">vv<<<^<^^>vv>v<<^^^v>v<v<^<^<^^>>>>v<<<v<^^^v<>v>^>^<<<<<^^>>>>>^^<v>vvv<<^>>>^^<<v>vv<<^>>"),
        new("Open", 10, "challenge", "v<<^>^>vvv>v<^^<v>v<<<v<^^^^^vvvvv<^>>>^>vv^^>v<<<v<^^<^^>vvvv<v"),
        new("Open", 11, "side", "<vv>>^<^>>^>"),
        new("Open", 12, "side", "^^^vvvvvvvvv>v<<vvv<vvvvv<v>^>vv<v>vvv>vvvvv<v>^>v>^"),
        new("Flip", 6, "challenge", "<vvv<v<^^^^^^^<<^>v>^^>^<<<>>v>^<^>>^>vvvv>>>vv"),
        new("Flip", 7, "challenge", "<vv<^^^^^^^^^^^vvvv^^^^^v^^^^^^^vvvvv^^^^^^^^^^^^vvvvvvvvvvvv<vvvvvvv<vvvvvvvv<vvvv"),
        new("Flip", 8, "challenge", "vvv>>^^vv<v<<^<^^vv>v<v<<<<<<<>>>>>^>>v<<<<<<>>>>>vv<<<<<<<v<<<<<<v<<<"),
        new("Flip", 11, "challenge", ">>v<<^^^>vv>v<<<>>>>vv<^^<^>>>v^^>vv>v<<<<>>>^>vvv>v<^^^<<<<<<"),
        new("Flip", 13, "challenge", "<vvvv<v>^^>>>^<<^<vvv<v>>^<<v>v<<<^<vv^^>>>>>>"),
        new("Flip", 14, "challenge", "<v<^>^^<^<vvvv^>v>^^v<^<^>>><<^>v<vv>>^<<v<^^^^vvvvvv<^>>>>v>>^<^<<vvvvvvv^^^^^^^>>vv<>^^<<vvvvvvv^^^^^><^^>>vv<<^>^>v<v>^>vv<<<v<"),
        new("Flip", 15, "challenge", "<^^^<v^>>>v<<<<<<<v>^v<<^^^^^vv^>^>>>>>^<vvvv<v>v>^^^^^v<<v>>>>>>>>"),
        new("Flip", 16, "challenge", ">vv<<v<^^^^^^vvvv>>vvv>>><<^>vvvvvv>v<<^<<v>>>>>^>vv<<<^^^^^^vvvv>>vvv>>><<^>vvvvvvvvvvv>v<<^<<v>>>>>>"),
        new("Flip", 17, "side", "v>>>>^<<^^^><v<^^<^<>>><<<v<^^>>^>vv>>"),
        new("Cycle", 6, "challenge", ">>>>>>>>>vv>>>>>>>>>vv>>>>>>>>>vv>>>>>>>>>vv>>>>>>>>>v<^^"),
        new("Cycle", 7, "challenge", "<^^^>^<<v<^^>^<<v<^^^^^^>^<<<<vv>>>>vvvvvvvvv>>>>>>>>^^^"),
        new("Cycle", 9, "challenge", ">><^><^>^>vvvv<<<<^^^>>>^>vv<vv>vv>"),
        new("Cycle", 10, "challenge", ">vvv<^v<<<^>>v>^^^v<<<^>>v>^^^>^^<<<<<"),
        new("Cycle", 14, "challenge", "<vv>>>^>>>vvv<<<^^^>^<<^<vvv^>>v<<<<^<<v>>>>^>>vvvvv^>vvvvvv"),
        new("Cycle", 15, "challenge", "vv<<><<<<<<vv^^<<><<<<<<vvv^^^<<<>><<<<<<vvvv^^^^^^^"),
        new("Cycle", 16, "side", "<^^>^>vvv<<v<<^>>><<<^^>>^>vvv>>>>vv^<vv>>>"),
        new("Cycle", 17, "side", "v>>vv<^^^^^^^>vvvv<<<^<^>><vv>^>^^v<v<^^>^<<<<<v>>>>^<<<>"),
        new("Cycle", 18, "side", "^>>>>v<<<<v<^>>>>>v>^<<<<v<^>>>>v<<^>>>^^<^vv<"),
        new("Player", 8, "challenge", "v>><v><v>^^<<<<v>>>^<v<^>^<>vvvv"),
        new("Player", 10, "challenge", "^>><vvv>^<<<<^<<v>>>^<vvv^>>>^<<<<<<v>>>>>v>"),
        new("Player", 11, "challenge", "^^<<v>>>>vvv<<<<^^><^^>>>>vv<v<^<^>><<<vv"),
        new("Player", 16, "challenge", ">>>>^^^<<<>v>>>>>^^^<<<^>vvvv<^^^>>>>v>>^^^^<<<>>>>"),
        new("Player", 17, "challenge", "v>>>><<<>>>><v<^^<^>vvvv<<<<v<<^>v>^^<^>vvv<<<v<<^<vvvv^^^>>>v<^^^^<^<<vv<<>>>>>v>>"),
        new("Player", 20, "challenge", "<<<vv>>^^^>>>^^^^^>^<v<^^^<^>^>>>>^<<v<vv<v>>^>vv<<<^<v>vv>"),
        new("Player", 21, "side", "^^<<<vv>^<vv>^<vv>^<v>>"),
        new("Player", 22, "side", "^>>^^<<v>>^^>^^>vv<v>^^^>"),
        new("Player", 23, "side", "<<<<^^^>>>>^^<<<^^>^^"),
        new("Player", 24, "side", ">>>^>>vv>v<<<^<><v>^^^^<<^^>>v><<^"),
        new("Possess", 2, "challenge", ">>^^vvvv<^><^<vvvv^^>^^<vvvvv>>"),
        new("Possess", 6, "challenge", "v<<^<vv>v>^^^<<^>>v>^^^^^>>^>>vvv<"),
        new("Possess", 9, "challenge", "<^>>>>>v<<<v>>>v<<<<^^^<^>v>^>^<v>^>^<^"),
        new("Possess", 10, "challenge", "v>>^^<<<^>>>>^^<v<v>>>><<vvv>v>"),
        new("Possess", 11, "challenge", ">>^^<<v<^v<^>^<<<v>^<<v<^^"),
        new("Possess", 12, "challenge", ">^^^>>^>vvvv>v<>vvv>v<v<^<<<v>>^^^^^<<<>>>>>>>><<vvvvvv<^^>vv<^^<^^>"),
        new("Possess", 15, "challenge", "^^^^^^^^vv<<<v>>>^>v<v>^^>vv<v><<<<<^>vvv<vv>^<^>>>>>>>^^^>>"),
        new("Possess", 16, "challenge", "^^<<<<<v<<vvv<<<^^^<^vv>>>v>^^^^^^<<>^<<vvvvvv>>>v^<<<<^^^^^^^<<<<vvv<<^^^"),
        new("Possess", 17, "challenge", "v<<v>^>>>vv<<<v>>>^>>>v<<<v>>>^>>>v<<<v>^>>>vvv<<<v>>>>^>^^<<<vvv<vvv>vvvv<<<<<<vv<<<<^^^^^"),
        new("Possess", 18, "challenge", "<^^^vv><vvv><vvv><vvv^><vvv><vvv^^><<^<v^<v^"),
        new("Possess", 19, "side", "^^><<>>>v<<<>>>v<<<>>>v<v<^v<^>>^<<vv<^^^^"),
        new("Possess", 20, "side", "v>^>v<v>><^^>>v^>>v<^<v>v<<^<vv^<<vv>^^vvv>^^^^<>>>^<<<vv<^>vvvv"),
        new("Possess", 21, "side", ">^^^>>vv>^^>v>v>^^^>>vvvvvvvvvv>>vvvvvvvvv"),
        new("Possess", 22, "side", ">^^^<vv<v>>>><<<^^<<<>>^^<>vvvv>^^<^^<^^<>vv>vv<<>>>>^^^>>>^>"),
        new("Wall", 6, "challenge", "<v>>^<v>^>v<<<v>>v>^>>><<<^<vv"),
        new("Wall", 8, "challenge", "^>>v<<<vv>v>>^^<<v>v>^^<^>v>^^^>^<<^<<v>^^^^^<<v>^<v>^>vv<^<<>vv<<"),
        new("Wall", 9, "challenge", "vv<<<<^>>v<^>>v<^^^>vvvvv^^<^>^>>>>>v<<^>v<<^>vvv<^^^^^v>v<^^<vvvvvvv>>>"),
        new("Wall", 10, "challenge", "v<<<^<^>>>^<<^<vv<vvv>>>>>>v>^^^><<v<^>^^>>>>>>>vv"),
        new("Wall", 11, "challenge", "^^^<<v<v>^>v>vvv<<<<<>^^v>v<<^^^>>>>vv<vv>^<^><<<<v<<<<^<vv"),
        new("Wall", 13, "challenge", "v<<<^^v>>>>>>><v<vv>^^<<^>>>>^<vvvv^^^^>>vvvv>v<<<"),
        new("Wall", 14, "challenge", "v<^>v>^^<^>>>v<^>v<vvv>^^^^>^<<>>^>vvvv^^^^<^<<<v"),
        new("Wall", 15, "side", "^^>>>>v<^>v<vvv<<<^>v^^>>^<<<^>v<v>v>^^^"),
        new("Infinite Exit", 4, "challenge", "^^^<<^>vvvv>>>^^<^^<v<^>>vv>^^^>"),
        new("Infinite Exit", 10, "challenge", "vv>>vvv>>>><<<v<^^^<^^v<<^^<<<^>vvv<v>>>^>><<<vv>>>>vv"),
        new("Infinite Exit", 11, "challenge", ">^^<<^<v>v<<<>^^vvvvv>v>^^^^^^^<v<^^>v<<<<<<<>>^^^^^^>>>vvvv"),
        new("Infinite Exit", 14, "challenge", ">vv<<<^<v^<<^>>>^>v<v>^^>vvvvvv>v<^<v>>v<^<vv<v"),
        new("Infinite Exit", 15, "challenge", "<^^^<^>>vvvvvv<^<^>>vv>^^<^>>><<^^^^<^^>v>^^^^^<<vvvvvv>>>><<<^^^^^^^^^^^^>>>>"),
        new("Infinite Exit", 16, "challenge", "v>vv>>>^<<^<<vv>>^^^<vv<v^<<vv>>>>^^^^>vvvvv<v>>><<<v>>>><^^>v>v<<v>v>^^^<^>>"),
        new("Infinite Exit", 17, "challenge", "<vvv>^<^>>>>v<<v<^^^^>>vv<v>><<<<^^^^^v<^^^"),
        new("Infinite Exit", 18, "challenge", "vv>>vvvv>vvv>v<^<vv>v<<<^^vvvvvvv<v>>^>v<<<vv<v>^>vvvvv<v>>>><<^<vvvv<v>>>^^<vv<v>^>vvvvvv<vv>vv^^"),
        new("Infinite Enter", 10, "challenge", "<^^^>vvv<v>^^^^>vv>>^<^<vvv^>>v<^<v<vv>^^^^<^>>>v>^<<<<<vvv<<^^<<"),
        new("Infinite Enter", 11, "challenge", "<^^^<v^>>>v<<^<vvv<v>^>vvv<v>vv<<^<<^<<v>>>>>vv>vvv^^^^<^>>vv<vv<vv>^^^^v<<vvvv<<<"),
        new("Infinite Enter", 14, "challenge", ">>>>^>v<v><v<v>>>v>^<<<^^^^>>v>v<<^<vvv<<^>^<<^<v<<><^^>v<v>><"),
        new("Infinite Enter", 15, "challenge", "<vv<v>^^>>>v<^<vvv>>>^<<>>>vvvvvvvv<<<<^<<<<<vvvv<v<v>>>>^>vvv<vvvvv<<<^<<<<<^<>vvvvvv<<v<^^>^^^^^<<vvv>^>v>v<<^<vvv>vv<<<<^<<<<<vv>>>v^<<vv>>>v<^^<^>>vvv>^^^>>>>^^<v>v<<<<>v<^^^>^<<<<<<><<^<v<v>^^^>>>vvv>v<vvvv<vvvvv<^^^^^>>^>v>vv<<"),
        new("Infinite Enter", 16, "challenge", "^^>v<^^>^<<^vv<^^>^<vvvv<<vv^vvvv>>^>^^^v>v<<vv<<vvv<^>>><<<vvv>v<^^v>^^<vvvv<<vvvvv"),
        new("Infinite Enter", 18, "challenge", "<<<<<<>>^>vv<v>>>>>>v>><<^<vvv>>>><<<vv<<^>^>vvvv<v>v^><<<<<vvvv<<<<v<<>^^^<^>>v>^v^^<<>v^>^<v<^>>^<<<v<^v<^^v>vvvvv<<<<<>>>>>"),
        new("Infinite Enter", 19, "challenge", "<<^^>>>>^>vv<v>v^^>>^^^>>>^v^^<<<^"),
        new("Infinite Enter", 20, "challenge", "<<v<^>^^^^<^vvv>>^^^>vvv<vv>>>v>^^^^^^"),
        new("Multi Infinite", 6, "challenge", "vvv<^<^>>vv>^^>^<vv<<vvvvv^^>>^^^^>^^<<<v>^>v^>v>><<^<vvvvvvvvv"),
        new("Multi Infinite", 7, "challenge", ">^^^>v>v<^<vv>v<^<vvvv<v>><^^^^>>>^^^v<<<^v<<^>>^v<<<^>><<vvv>>>>>v>^^^<<<>>>^vv<<<<<^><^>><v>><^>><v>>><<^>v>>^v<<^>><<<<<<<<<vvvvvvvvv"),
        new("Challenge", 1, "normal", ">^^^>>^<^<vvvv>>v<<<<<>^<<^><^^>>^>vv>>>v<^^<^<vvvv<vv<^^<^^>v<v>><^^>>vv<vvv>>^^^^"),
        new("Challenge", 2, "normal", "v>>^^^^^vvv<<<^><^<<>vvvv<<^>v>^^>>^^^<v>v<^<vvv<<<^<<v>^^>^^<v>v<<vv<^<^>>v>^^^vv<<<^<<>>>v>^^<<<vvvvvvv>vv<v>v>^^>^"),
        new("Challenge", 3, "normal", "^^<<<^>v>>>>>^^^<v>vv<<<<<^>>v>>>^^>^<vvv<<<^>v>>^^vv<<^>v>^<>>^<<>>^<<<<<<<<>vvv<"),
        new("Challenge", 4, "normal", "<vvv>^<^>>><vv>^<^>>>>vvvv^^^^^^^^<^>>>>>>>^v<<<<<vv<v>^^^^<vvv<v>>>>>^^^^vvvvvvv<v>>>>>v"),
        new("Challenge", 5, "normal", "v<>vv<^v>>>^^<>vv<^>^<<<^<vvv>v<v<<^>>^^<<vv^<v<v>>>>>v>>^^<v>v<>>^^^<^<vvv>v<<<<^<v<v>>>^^>>^^^^<<<"),
        new("Challenge", 6, "normal", "v>>>v<v<^^^v>^>^<<v<^^^^^^<<<<v>>^<>vvvv<^^^^<<<^<vv>>"),
        new("Challenge", 7, "normal", "^>^^^>v<v>>v>^<<<v<vv>vv><v<^<^>^>v<<<vvv<vv>vv>><<v<^vv<<vv>vv^><^<^<^^>^^^^>vv<vv<vv>vv<^>>>v>^^^<>^<^<^<"),
        new("Challenge", 8, "normal", "^>>>v<v<^>>^^^<v>v<<<v<^>>^^<v>v<^^<<v>^>v>v<v<^^<^>>><<<<vv<<>>^>vv^<<<<v<<<<v<<<"),
        new("Challenge", 9, "normal", ">>^^^^<vv>v<<v<^v<^<^>>>><<<^^>vv<v><v>v>^^^^vvvv>^^^>^<vv<v<^^^<^>^>vvvv^^^<v>>v>^^<^>><vvv>>>><^<vvvv^^^<<<>>>^>vv^<<<vvvv^>^<<<<>>>^^^v<<vvv>>>><^^^^<<<>^^<<<vvvv^>>>>^^^<<vvvvvvv>>"),
        new("Challenge", 10, "normal", "vv>v<<<>>>>>^^^<<<<<^<vvv^^^^^>>>>>><<<vvvvvv<<>>^^^>^>><<<vvvv<<<vvvv^^^^<^>v>^v>^<v<^^<^>vvvvv>>>>>^^^^^vvv<<<<<<vvv<<<<>>>v>^<^>><^^^>>"),
        new("Challenge", 11, "normal", ">>>>^^^^>^^>>^^^>^^^>^>>^>>>>^^^^>^>>>>^>>^^^^>>>>vv<<<<^^^v>>>><^^^^v>>>>><^^^^v>><vvvvvvv>><^^^^^vvv>>>>>>>>><^^^^vvv>>><^^^^^vvv>>>><^^^^^^vvv>>><^^^^^^^vvv>>>>><<<vvvvv<<<"),
        new("Challenge", 12, "normal", "<<>^>^>^<v<^^<<vv>>>>>vvv<<^^^<^>>v>^<<^^<<<<<<<<<<<<<^^^^^^^^^^^^^^<<"),
        new("Challenge", 13, "normal", ">^>v>>>>>><<>>>>>>><<vvvvv^^vvvvv^^<<<>><<<>>vv>"),
        new("Challenge", 14, "normal", "<<<<<<<<>vvv<<<<<<<<<>>>>>><<<vvvvv<v>^^^^^^<<<<<<<>>>>>>>><<<vvvvvv^^^^^^<<<<<<<>>>>>>>><<<vvvvvv><^^^^^^<<<<<<<>>>>>>>><<<vvvvvv"),
        new("Challenge", 15, "normal", ">>>>vv^^<^^^>^<<<<<^^^><vvv>v^>>>>v^<<<<<<vvv^^^>^^^^^<^<<<<<^^^^^><vvvvv>v^>>>>>>vvvv^^^^<<v<<<^^^<^<^^^<>vvv>v^<^^^^^>>vvvvv<v"),
        new("Challenge", 16, "normal", "v>>>^<v<^^^v<<^>><^>vv>^^^^>^<v<^>>^<vvvv>>>v<^<v>v<v<^^^^^<^>v>^>^<<^<vvvvv<vv>^^^^^<^>>vvvvvvvv>>>>>><<^^^^^^^"),
        new("Challenge", 17, "normal", "<<<<<^^>^^>>>v<<<^<^>>>v<<<vv>>>>^<<v<^<^>>>>^<<<<v>>>>^<<v<<>>>v<<<^>>>>v<<<<^>>>>vvvv>>>>>vvv<<<<<<>^>>vvvvv>>>>>>>>>v>>>>>vv>>>>>>>v>>>>>>>>"),
        new("Challenge", 18, "normal", ">v^>>^>>>v<<<v^>>>^>v<<<<v>>^>>^>>>>v>>>vv>>>vv<<vv<<v<<<v^>>>v>^<<<<v>^>>>v>>>^<<v<<^^^>>>>>^^>>>>^^^"),
        new("Challenge", 19, "normal", "v>vv>^<<<<<>>>>^v>^vvv^^<<vvvvv<<<<<>>^^^^v>>>^<<<<v>v<<<<<>^^v>>>>vv<<<>^^^>>>>"),
        new("Challenge", 20, "normal", ">>^>>v>>^><"),
        new("Challenge", 21, "normal", "^^^<vvv<<<^^^<<vv<<<^^>"),
        new("Challenge", 22, "normal", ">^<^>>>>^<>vv<^^^^^>^<vvvvvv<<<<v>^^^^^^<^>vvvvv>>^^vvv<v>>>>>^>v<<<<<<<^^^>>>>>>^>v<<<<<<<<vvvv"),
        new("Challenge", 23, "normal", "^^<<<^^>^<v>^<v>^<v>^<v>^<v<^>>v<<^>>vv<<^>v<^>v>^<<v>>^<<v>>v^<v^>v^>v^^vv^>v>>>^>"),
        new("Challenge", 24, "normal", "^^^^^^>^^^>^>^^^^^<<<<<vvv<^^<<<<<<<<v<^^v><^^^^^^^v>^^^>v<v^^^^^<<<<<<^^<vv^^>>>>>><<<<v>^>^<<^<^^^^^^<v>vvv"),
        new("Challenge", 25, "normal", ">vvvvv>>>^^^^^>><^<vvvvv<v>^^^^>vvv^^^^^<<^<<<<<vv>>vvv<<^^>^<<<<^<vv>v<^<"),
        new("Challenge", 26, "normal", "^<<^^v<v>^>v>vv<<^^^^<vvv>>>^>vv<v>>^<<^^^^<vv<^>vv>^^^<<<vv>>v>^<v><^^^>>vv<>vv<<<^^^>vvv<<v"),
        new("Challenge", 27, "normal", "^<<<v>>^^^<vv<v>v>>^v<<^>^^^>>v<<>>v<^<v<v>^^^<vv<v>>>>>>^>>vvv<<^^>>^>vvvvvv<v>^>>v<<<v<<<<<<vvvv<^>>v>>^^<v>v<^<vv<v>>>>>>^>vvvvv<^>>v>>^^<v>v<^<vvv<v>>^^>^^^<vv>v<^<vv<v>>>>>>>>^>vvvv<vv>>"),
        new("Challenge", 28, "normal", "<<<^<vvvv>>^>>>^>^v<<^^>>^>>^^>>>>>>vvvv>>^>>>^>^^vv<<^^>>^>>^^>>>>>>vvvv>>>>v"),
        new("Challenge", 29, "normal", "<vv<v<v>>^^>>>>v<<>>^^<<^<vvv<v>>^^^^<<<v>^>vvv>vv>^>^<<^<v<v>>v>^^>^<<^<<<<vv>>^^>vv^^<<vv<v>>^>>>vv<^>^<^<vv>vv<^<v<v>>>>>v>v>^>>v>^>>^"),
        new("Challenge", 30, "normal", ">v>^>^^<vv<v>>v>^<^>>vv>>>^^^^^^^^^<^>vv>>>^^^^^<^^"),
        new("Challenge", 31, "normal", ">^>>>^<v<<^>>v>^^v<<^<<<vv<^^v>>>v>^^<<<<^<^^>>^^^<^^^^>^<^^>>^^^<<^^>>>^^^<^^>>^^^<<<<<<"),
        new("Challenge", 32, "normal", "<<vv>>^<v<^>^<v<^^^vv>>>>>v>^^vvvv<^<<^>^>vv>v<<<<>>^^^^^>>^^"),
        new("Challenge", 33, "normal", "<vvv>^^^^^^<^>^v>vvv<v<^^^<^><<^^^^^>>v>>>vv<<<<<^<v>>vvv>>>^^^^>^<<<<<<v<^^^^>^<<<v<^<<<^^^^^^>>v>^^>^<<<<<<^<v<>^>>>>^^<<<<v<^^^^<^>>>>vvv>^^^^^<^>vv>>>vvv<<<<v<^^^^^^^^^<<<^^^<<v<^^^^^^<^>^v<vvvv<<^^^^^^^^^<^>>^>vv<vvvv<<^^^^^^^^v<<^>v>^^^<^^<<<v>>>><^>>v<v>^^^>vvvvvv"),
        new("Challenge", 34, "normal", ">>>v>><<^<<<^^^^>^>>>>>v<<v<^>^<<<v<<<^<<v>>>>vvvvvvv<^>^<vv<<<^><vv>v>^^^>^<v<^^<^><^>^>v^>>v<^<v>v<^<vv<v>v>^><<<<^<<<<v<v<^<^>>>^>vvvv<v><^^>vv<v>v>^^<"),
        new("Challenge", 35, "normal", ">vvv>v<^^<<<<<^^>>>>^^>vvvvv>v<^^<<<^>>>>><<<<<^^>>>>>v>>"),
        new("Challenge", 36, "normal", "<^^^>^<vv>>>v<<v<^^^>>>vvvv<v<^^^^^vvv<<v>><<^^^^^vv>>>>vv<^<v>>vv<^^^^^^vvv<<v>>>^>vvv<v><<^^<^^^^^vvv<<v><vv>>^^^^^vvvv<v<^^^^^>>>^^<<<<^^^>>^><v<^<<vvvvvvv<v>>>><<^^^^^^^^<<<<^^^>>>>>^v<<<<^<<<vvvvvvv<v>>>>><<^^^^^^^^<<<<^^^>>^>><<v<^<<<<vvvvvvv<v>>>>>><<<<<^^^^^^^^<^^^>>>>>^^"),
        new("Challenge", 37, "normal", "v>>^^^<^>vv>v>>^^<>v<<>^<<v<<^^^>v<v>>><<<v>>>v>>^^<<v<^<^>^<v<v>>>v<v<v><<^<^>v>>v>>v>^^^^vv<<<^^^^^>>>v>>^^^<<<^>v<vv><^<vv<^>v>^^>^^<<v<vv>^^<^>>>vv<<<^^^^^>>>v>>^^^<<<^>v<<v<^v<^^^vv>^<<^^^>v>v^<vv>>><<<<v>>>^>>vv<<<^^^^^>>>v>>^^^<^>v<<<<v<^^^^^^v>>>>>v>>^^^^^"),
        new("Challenge", 38, "side", "vv<<v>v>vv<<<<<>>>>v>>>>^^<^^vvv>v>vv<<<<<>><<<^>vvvvv>vv<^^^^^^^^>^<<<^<vv>v>vv<<<<<<>>>>v>>>>^^<^^>>^^^v<<<vv>>><^^>v<v>>v>>>>^^<^^>>>>^"),
        new("Gallery", 1, "normal", ">>>^<^<vv>>v<<<<<<<<<v<>^>>v<^^^^>^^<vvvvvvvvv<vvv^^^>^^<v>>>>^>>v<<<<<<<<v<<>>^>>v<^^^^>^^<vvv<v>>>>>>>"),
        new("Gallery", 2, "normal", "^>>>vvv<^^<^>>>>v>^>^<<<<^^>v<v>>>^>>v<<<>^<v>>>v"),
        new("Gallery", 3, "normal", "<<v<v>^>vvvvvvv>>>>v^^>^<^<vv<v>^<<<<vvvvvvv^^>^<<<v<<<>>>>>^>>>"),
        new("Appendix: Priority", 1, "normal", ">>vvv<<v<^^v>>^^>^<<<^<v<v>>>>v>^^>^<<<^^^"),
        new("Appendix: Priority", 2, "normal", ">>>^^<<^<v<v>>^>v<vv<vv>^^^>^<v<<v<<^>>v>^>^^^"),
        new("Appendix: Priority", 3, "normal", "v>>>>>>>>^^^^^^^^<<<<<<<^<vvvvvvvv<v>>>>>>>>v>^^^^^^^^vvv>v<<^<<<<<<<vvvvvvvv>>>>>>>^^"),
        new("Appendix: Priority", 4, "challenge", ">vvv<^v>>>^<<^^<v<v>>v>^^^^^vvvvv>^<<^^>v<<<v>>v>^^^<^>v>>^<<<^>v^<<<v>>>^<<<<"),
        new("Appendix: Priority", 5, "challenge", "^^^<v^^><<vv>^^v>^<v^<v<^<vv>^^<^>^"),
        new("Appendix: Priority", 6, "challenge", "<<^>>v<^>>v<v>^>v<vv<^>^<>>^<v<^>^<v<^>^<v>vvv<^>^<^<vv^^<<<<<"),
        new("Appendix: Priority", 7, "challenge", ">>>>vvvv<^^^>v<^^>^<<<v>v<<<^>v<<<^>^>>v<v>>^>vvv<<<<<^<<v^>>>>vvvvv>>>>v<^^^>v<^^^>v>v<v>>>^<v<^>vvv<<^^^^^>^^<>vvvv>>>>>vvvv><v<^>vvv<^<^^>v<^^^>v<^^>vvvvvv<<<"),
        new("Appendix: Priority", 8, "challenge", ">vvv<<^>>v>^<<<v<<^^^>>>^>v<vv<<>v>^<^^^>>>v>>^<<<^>>>^<vvvv>v<<<<^^>^^<vv>v<^^<>^>v>v<<^<<<vvv>vv<^^^>^^<<<<^^>>>>^>vv"),
        new("Appendix: Priority", 9, "challenge", "<<<^^>>>^>>>^^<<<v<<^>>>>vv<<v^>vv>vv>^^^^^vvvv<<v<<^<<v>>^^^^^<<vvvv>>>^^>^<<^^>>v<^<v>vvv>>vv<<<<>>>^^^v<^>v>>^^<"),
        new("Appendix: Extrude", 1, "normal", ">>>>>>><<>vv<<^^^^^^vv^>>vv<<<<<<><"),
        new("Appendix: Extrude", 2, "normal", ">>>>>>><<<v<^^^^vvvv<<>^>v<vvv^^^^<^^>vv^^^v"),
        new("Appendix: Extrude", 3, "normal", "^^<^>>v<v>^^^>vvvvv<v>^>vvvvv>>^^^^>>"),
        new("Appendix: Extrude", 4, "challenge", "^>^^<vv>v<<<<^^v>vvv^<<>>v>^^>^<<<<<<vv>>>v"),
        new("Appendix: Extrude", 5, "challenge", ">vv<v<^>^<<>^^<v>vvv<<^>v>^>^<<<<<<<<<<v<^^>^<vvvvv"),
        new("Appendix: Extrude", 6, "normal", "v>>>>><<<<<^^^^^vvvvv>>>>><<<<v<<^>>>v>>^^^<v>^>v<v>^>vvvv<v>>^>>v<<<v<<^^^>v<<<v<^vv>>>>>>>vvvv<"),
        new("Appendix: Extrude", 7, "normal", "<<<^^^^v>v<<<<v<^^^^^v>vv<<<^<v>>>^<^>>>>><<<<<<<vvvv>>>^^^^>>>>><>^^^^^>^^^"),
        new("Appendix: Extrude", 8, "challenge", "vv<<<^<^^^<<^<vv<<<^"),
        new("Appendix: Inner Push", 1, "normal", "v<<vv>>>>>^^<<<<<^<>^>>>^<vv>^<^>vvvv>"),
        new("Appendix: Inner Push", 2, "normal", "vvvv^>>>>>>>^^^^^v>^>v^<<<<<<vvvvvv^>>>>>v>>>>vvv^<<<<<v<"),
        new("Appendix: Inner Push", 3, "normal", "vvv>^<<<^^<^>>>^^^<<<^>>>><<v<<vvv"),
        new("Appendix: Inner Push", 4, "challenge", "<vvvv>>^^^>vvv<<<v<^^>^>v>v<<<<<<^^>>v<v<<^^^"),
        new("Appendix: Inner Push", 5, "challenge", "v<<<^>v<^^^^^^^^^^v<v>^<vvvv^^^^^vv<v><v>^>>^>v<^^^^"),
        new("Appendix: Inner Push", 6, "challenge", "vvvv<^>^^<<>^^<v>>vvv<^>^<^<<v>>vvv<<^>v>^>>^^^<v>v<^^^^^<<v>>vvv>v<<<<^^"),
        new("Appendix: Inner Push", 7, "challenge", "vvvv>>^v>>^<v<^^^^^^^v<^v<<vvv<vvvvv>>>vv^<v>>>>><<<^^^>>><<<<<^^^^^>>>>><vvvv><vvv<<<<<<<<^^^<<>>>>"),
        new("Appendix: Inner Push", 8, "challenge", "^^^^^^^>^<<<vvv"),
    };

    public static ExtraPuzzle? Find(string hub, int id) =>
        ALL.FirstOrDefault(p => p.hub.Equals(hub, StringComparison.OrdinalIgnoreCase) && p.id == id);

    public static IEnumerable<ExtraPuzzle> ForHub(string hub) =>
        ALL.Where(p => p.hub.Equals(hub, StringComparison.OrdinalIgnoreCase));

    public static void PrintIndex() {
        Console.WriteLine($"Extra solutions: {ALL.Count}");
        foreach (IGrouping<string, ExtraPuzzle> g in ALL.GroupBy(p => p.hub)) {
            Console.WriteLine($"  {g.Key}: {string.Join(", ", g.Select(p => $"{p.id}({p.kind[0]})"))}");
        }
    }

}
